수업

실습02- class

In [3]:
class Character:
    def __init__(self):
        self.health= 200
        
    def move(self):
        self.health-=10
        
    def rest(self):
        self.health+=10
        
    def checkHealth(self):
         print("Health:",self.health)

In [4]:
class Knight(Character):
    def move(self):
        self.health-=15
        
    def attack(self):
        print("공격합니다")
        
    

In [7]:
knight_1=knight()
knight_1.checkHealth()

NameError: name 'knight' is not defined

In [6]:
class Healer(Character):
    def __init__(self):
        
        self.mana = 100
    
    def heal(character):
        self.mana-=10
        character.rest()
        
    def checkMana(self):
        print("현재 mana:",self.mana)

In [8]:
healer1= Healer()
healr.checkhealth()

NameError: name 'healr' is not defined

In [15]:
x= np.arange(20)
x

NameError: name 'np' is not defined

In [13]:
print(x[1:3])

NameError: name 'x' is not defined

In [16]:
print(x[1:3,1:3])

TypeError: list indices must be integers or slices, not tuple

In [26]:
x = np.arange(10)
   

NameError: name 'np' is not defined

In [24]:
 a= np.arange(20).reshape(4,5)

NameError: name 'np' is not defined

In [30]:
a = 13
b = 9

a & b

9

In [32]:
np.random.rand(5,5)

NameError: name 'np' is not defined

In [34]:
np.random.randint(1,10)

NameError: name 'np' is not defined

In [37]:
x = np.rando.randint(1,10,size=(5,3))

NameError: name 'np' is not defined

In [38]:
x.ravel()

AttributeError: 'list' object has no attribute 'ravel'

In [40]:
x=np.arange(1,4)
y=np.arange(4,7)

np.concatenate([x,y])

NameError: name 'np' is not defined

In [41]:
import numpy as np

In [43]:
x = np.array([1,2,3])
x+=1
x

array([2, 3, 4])

In [58]:
x= np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
y= np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)

x+y


array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [59]:
x*y

array([[ 10,  40,  90],
       [160, 250, 360],
       [490, 640, 810]])

In [64]:
array = np.linspace(1,20)
print(array+10)

[11.         11.3877551  11.7755102  12.16326531 12.55102041 12.93877551
 13.32653061 13.71428571 14.10204082 14.48979592 14.87755102 15.26530612
 15.65306122 16.04081633 16.42857143 16.81632653 17.20408163 17.59183673
 17.97959184 18.36734694 18.75510204 19.14285714 19.53061224 19.91836735
 20.30612245 20.69387755 21.08163265 21.46938776 21.85714286 22.24489796
 22.63265306 23.02040816 23.40816327 23.79591837 24.18367347 24.57142857
 24.95918367 25.34693878 25.73469388 26.12244898 26.51020408 26.89795918
 27.28571429 27.67346939 28.06122449 28.44897959 28.83673469 29.2244898
 29.6122449  30.        ]


In [65]:
import pandas as pd

In [67]:
x=[1,2,3,4,5]
s= pd.Series(x)
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [69]:
x=pd.Series(x,index=['a','b','c','d','e'])

In [70]:
x

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [71]:
x= {"수학":90, "영어":80,"과학":95,"미술":80}
x=pd.Series(x)

In [72]:
x

수학    90
영어    80
과학    95
미술    80
dtype: int64

In [73]:
x['수학']

90

In [74]:
x['영어':]

영어    80
과학    95
미술    80
dtype: int64

In [77]:
x = pd.Series(x,index["수학","영어"])

NameError: name 'index' is not defined

In [82]:
student_1= {"수학":90,"영어":80,"과학":95,"미술":80}
student_2= {"수학":70,"영어":90,"과학":100,"미술":70}

In [84]:
x2= (x1[0:2,5:10,5:10] )
printx2

NameError: name 'x1' is not defined

In [91]:
import numpy as np

In [92]:
x= np.random.randint(1,101,size=(10,10))

In [ ]:
S_1=np.where(S>=50,1,2)
S_1

In [94]:
import pandas as pd